sudo: false

language: rust
cache: cargo

os:
- linux
- osx

rust:
- nightly
- beta
- stable

addons:
  apt:
    packages:
    - libssl-dev

script:
- |
  cargo build &&
  cargo test &&
  cargo doc
- if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    cargo build --no-default-features;
  fi

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh);
    cargo tarpaulin --no-count --ciserver travis-ci --coveralls $TRAVIS_JOB_ID;
  fi
