[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Philip Craig <philipjcraig@gmail.com>"]
name = "object"
version = "0.7.0"
description = "A unified interface for parsing object file formats."
keywords = ["object", "loader", "elf", "mach-o", "pe"]
license = "Apache-2.0/MIT"
repository = "https://github.com/gimli-rs/object"

[dependencies]
goblin = "0.0.13"
uuid = "0.5.1"

[dev-dependencies]
memmap = "0.6"

[features]
nightly = []
