[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "object"
version = "0.2.0"
description = "A unified loader interface for the target platform's object file format."
keywords = ["object", "loader"]
license = "Apache-2.0/MIT"
repository = "https://github.com/gimli-rs/object"

[dependencies]
xmas-elf = "0.4.0"

[target.'cfg(target_os="macos")'.dependencies]
mach_o = "0.1.2"
