[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Philip Craig <philipjcraig@gmail.com>"]
name = "object"
version = "0.5.0"
description = "A unified interface for the target platform's object file format."
keywords = ["object", "loader", "elf", "mach-o"]
license = "Apache-2.0/MIT"
repository = "https://github.com/gimli-rs/object"

[dependencies]
goblin = "0.0.12"

[dev-dependencies]
memmap = "0.6"

[features]
nightly = []
