[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Philip Craig <philipjcraig@gmail.com>"]
name = "object"
version = "0.7.0"
description = "A unified interface for parsing object file formats."
keywords = ["object", "loader", "elf", "mach-o", "pe"]
license = "Apache-2.0/MIT"
repository = "https://github.com/gimli-rs/object"

[dependencies]
scroll = "0.9"
uuid = "0.5.1"
flate2 = { version = "1", optional = true }

[dependencies.goblin]
version = "0.0.15"
default-features = false
features = ["endian_fd", "elf32", "elf64", "mach32", "mach64", "pe32", "pe64", "archive"]

[dev-dependencies]
memmap = "0.6"

[features]
std = ["goblin/std"]
compression = ["flate2"]
default = ["std", "compression"]
