[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "object"
version = "0.4.1"
description = "A unified interface for the target platform's object file format."
keywords = ["object", "loader", "elf", "mach-o"]
license = "Apache-2.0/MIT"
repository = "https://github.com/gimli-rs/object"

[dependencies]
goblin = "0.0.11"

[features]
nightly = []
