[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "object"
description = "A unified loader interface for the target platform's object file format."
keywords = ["object", "loader"]
version = "0.4.0"
license = "Apache-2.0/MIT"
repository = "https://github.com/gimli-rs/object"

[dependencies]
goblin = "0.0.10"

[features]
nightly = []
